# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_title', models.CharField(blank=True, max_length=50)),
                ('video_hash_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), size=None)),
                ('group_hash_id', models.CharField(default=video.models._generateHash, max_length=8, unique=True)),
                ('generated_datetime', models.DateTimeField()),
                ('memo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(default='none', max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_value', models.CharField(default=video.models._generateHash, max_length=7, unique=True)),
                ('person_path', models.FilePathField()),
                ('feature_path', models.FilePathField()),
                ('score', models.FloatField()),
                ('frame_num', models.IntegerField()),
                ('shot_datetime', models.DateTimeField()),
                ('probe_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TestVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='assets/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_value', models.CharField(default=video.models._generateHash, max_length=7, unique=True)),
                ('video_path', models.TextField()),
                ('time', models.DateTimeField(blank=True)),
                ('memo', models.TextField(blank=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('total_frame', models.IntegerField(default=0)),
                ('frame_rate', models.IntegerField(default=0)),
                ('is_detect_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
