# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 01:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinate', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), size=None)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_path', models.TextField()),
                ('running_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
