# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='frame_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='total_frame',
            field=models.FloatField(default=0.0),
        ),
    ]
