# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeList',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Person')),
            ],
        ),
    ]
