# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 19:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadlist',
            name='total',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), default=list, size=None),
        ),
    ]
