# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='video_hash_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=7), size=None),
        ),
    ]
