# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('bbox_img_path', models.TextField()),
                ('feature_path', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='person',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
