# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20171013_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='frame_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='total_frame',
            field=models.IntegerField(default=0),
        ),
    ]
