# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_probelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='feature_path',
        ),
    ]
