# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20171203_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('U', 'Undefined'), ('P', 'Positive'), ('N', 'Negative')], default='U', max_length=1),
        ),
    ]
