# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170913_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='running_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
