# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20171003_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
