# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20170913_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='running_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.TextField(unique=True),
        ),
    ]
