# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('U', 'Undefined'), ('P', 'Positive'), ('N', 'Negative')], default='U', max_length=1),
        ),
    ]
