# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20171013_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bbox_path',
        ),
        migrations.AddField(
            model_name='person',
            name='frame_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='person_path',
            field=models.FilePathField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='feature_path',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(upload_to=''),
        ),
    ]
