# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
