# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20171018_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FilePathField(),
        ),
    ]
