# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20171109_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
