# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20171109_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='shot_datetime',
        ),
        migrations.AddField(
            model_name='person',
            name='shot_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
