# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20171019_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hash_value',
            field=models.CharField(default=video.models._generateHash, max_length=7, unique=True),
        ),
    ]
