# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_video_hash_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hash_value',
            field=models.CharField(default=video.models._generateHash, max_length=7, unique=True),
        ),
    ]
