# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20171023_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(default='none', max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGroup',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_hash_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), size=None)),
                ('group_hash_id', models.CharField(default=video.models._generateHash, max_length=8, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='is_detect_done',
            field=models.BooleanField(default=False),
        ),
    ]
