# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 10:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20171024_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_title', models.CharField(blank=True, max_length=50)),
                ('video_hash_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), size=None)),
                ('group_hash_id', models.CharField(default=video.models._generateHash, max_length=8, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VideoGroup',
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.DateTimeField(default='2017-01-01'),
        ),
    ]
